### ISSUE TITLE
bug when position is initially set to either 0 or 100

### ISSUE THREAD

**Issue by moloko** [nerdyman/react-compare-slider#37]
I can replicate both these issues using the example in this GH repo.

If you initially set `position` to `100`, the handle is placed on the exact opposite side to what you'd expect.

Whereas if you set `position` to `0` the handle is in the correct position but `itemOne` is being displayed when it should be hidden.

Here's a screenshot of it set up with `100`:
![Screenshot 2021-05-27 at 17 52 26](https://user-images.githubusercontent.com/1249597/119866090-51597380-bf14-11eb-85a0-c994e39fa5fc.png)

In the example, it seems to be slightly specific to the size of the browser viewport i.e. if I have my browser maximised it works fine for `position: 100` but still has an issue with `position: 0`.

I did a bit of debugging and the problem seems to lie around here: https://github.com/nerdyman/react-compare-slider/blob/f552b1f536c742269c8d92b20d2ddcc7ac92a451/src/ReactCompareSlider.tsx#L184-L198

Specifically that on some occasions it's returning on L197 when, under normal circumstances (e.g. position being set to 99) it would not.

One workaround I've found is to set the initial position as a String rather than a Number

**Comment by moloko** [comment]
can also workaround issue by initially setting `position` to either `0.1` or `99.9`.

**Comment by moloko** [comment]
> Do you know which resolution it breaks at?

Most of them TBH! It was just one time I had my browser window maximised when I ran it that I noticed position: 100 was working fine, am away from my main computer right now but I think it's 1920 x 1080. Note that it's only ever on load that it breaks, when you resize the browser it corrects itself/just works.

**Comment by moloko** [comment]
> I think it's 1920 x 1080.

Nope, is actually 1680 x 1050

**Comment by nerdyman** [comment]
@moloko I dug into this a bit at the weekend and think it's happening because it needs to call `updateInternalPosition` at least once when it mounts but the bounds check cause it to exit out on the first call.

I'll open an MR soon to fix it :)

**Comment by nerdyman** [comment]
@moloko This has been fixed on the `next` branch if you want to take a look. I'll be publishing a new version within the next week.

**Comment by nerdyman** [comment]
@moloko This has been published in [v2.0.3](https://www.npmjs.com/package/react-compare-slider/v/2.0.3).

**Comment by moloko** [comment]
@nerdyman brilliant stuff, thanks. I'll update this week at some point.

**Comment by serban-mihai** [comment]
This is still happening to me with **v2.0.3**
Looks like the `position` argument is ignored at all, no matter what I pass as a value the first render will always have the cursor to 0 and the first image overlapped to the second, on the first move event everything comes back to normal.
Same thing is happening even if I don't declare the `position` argument, that should default to 50. 

Any idea?

**Comment by nerdyman** [comment]
@serban-mihai Have you got a repro? It's working in the [live docs](https://react-compare-slider.vercel.app/iframe.html?id=demos--position&viewMode=story) and [in a sandbox](https://vspw1.csb.app/).

Could it be that the components you're comparing initially have `0` width or height when they first render? That could maybe cause the position to be calculated incorrectly although I haven't seen it happen before.

**Comment by moloko** [comment]
I tested the updated version and it seemed fine to me. Can give it a retest when back at work on Thursday.

**Comment by serban-mihai** [comment]
> @serban-mihai Have you got a repro? It's working in the [live docs](https://react-compare-slider.vercel.app/iframe.html?id=demos--position&viewMode=story) and [in a sandbox](https://vspw1.csb.app/).

@nerdyman Sadly I cannot share the entire repo, but the problem might be on my side.
The stack I'm working with is made by  Tailwind, Framer Motion, Next.js and a different Image Loader: [react-optimized-images](https://github.com/cyrilwanner/react-optimized-image)

The code where the react-compare-slider is declared looks like this:

```
<ReactCompareSlider
    position={50}
    portrait={portrait ? true : false}
    handle={
      <ReactCompareSliderHandle
        buttonStyle={{
          backdropFilter: "blur(2px)",
          background: "white",
          border: 0,
          color: "#333",
        }}
      />
    }
    itemOne={
      <Img
        className="cursor-pointer rounded-lg object-cover w-full"
        src={require(`../assets/images/${firstSrc}`)}
        alt={firstParsedAlt}
        width="100%"
        height="100%"
        draggable={false}
        webp
      />
    }
    itemTwo={
      <Img
        className="cursor-pointer rounded-lg object-cover w-full"
        src={require(`../assets/images/${secondSrc}`)}
        alt={secondParsedAlt}
        width="100%"
        height="100%"
        draggable={false}
        webp
      />
    }
  />
```
That <Img /> will output into a picture set that is going to also convert the image in webp at build time.
After parsing, the DOM looks like this:

```
<div>
      <div id="octaphonic-case" class="flex flex-col items-center justify-center w-full rounded-lg" style="opacity: 1; transform: none;">
          <div style="position:relative;overflow:hidden;user-select:none;-khtml-user-select:none;-ms-user-select:none;-moz-user-select:none;-webkit-user-select:none" data-rcs="root">
              <picture>
                  <source type="image/webp" srcset="/_next/static/chunks/images/pickup-printed-54c889a0e8fc1c76e2cae8a0ad2e29f2.webp"/>
                  <source type="image/png" srcset="/_next/static/chunks/images/pickup-printed-750e0948cb90b171e7c19dd43344bce7.png"/>
                  <img src="/_next/static/chunks/images/pickup-printed-750e0948cb90b171e7c19dd43344bce7.png" class="cursor-pointer rounded-lg object-cover w-full" alt="The final concept of the Octaphonic Pickup 3D Printed" width="100%" height="100%" draggable="false"/>
              </picture>
          </div>
          <div style="position:absolute;top:0;left:0;width:100%;height:100%;will-change:clip;user-select:none;-khtml-user-select:none;-moz-user-select:none;-webkit-user-select:none" data-rcs="clip-item">
              <picture>
                  <source type="image/webp" srcset="/_next/static/chunks/images/blender-pickup-bbe0fc472ffc4e00e1454ec8d823e783.webp"/>
                  <source type="image/png" srcset="/_next/static/chunks/images/blender-pickup-14634a0d4a0cb449d00da2137c248c1c.png"/>
                  <img src="/_next/static/chunks/images/blender-pickup-14634a0d4a0cb449d00da2137c248c1c.png" class="cursor-pointer rounded-lg object-cover w-full" alt="The final concept of the Octaphonic Pickup in Blender 2.81" width="100%" height="100%" draggable="false"/>
              </picture>
          </div>
      </div>
  </div>
```

> Could it be that the components you're comparing initially have `0` width or height when they first render? That could maybe cause the position to be calculated incorrectly although I haven't seen it happen before.

It might be but I don't think so, that `w-full` under the **className** of the <Img /> it's the same as `style={{ width: "100%" }}`

I did 3 browser refresh in the above example:
![output](https://user-images.githubusercontent.com/34487580/127213918-1588c3e3-32b4-4f7e-bf05-f2fbc5f199eb.gif)

**Comment by nerdyman** [comment]
Is the zoom in effect being handled by framer? It could be that the width or height at the point it mounts is zero.

I'm happy to dig into this more but could you [open a discussion](https://github.com/nerdyman/react-compare-slider/discussions) for your usecase specifically? I don't think it's related to the changes in this issue.

**Comment by serban-mihai** [comment]
@nerdyman You're right, thanks for the tip anyway, I'll try to see if this might be the problem, that zoom in effect is indeed handled by framer, just a fade in animation for when the component is in view.

I'll let you know if I found the source problem, I'll also disable it to see if the cursor works properly,
Thanks again!

**Comment by nerdyman** [comment]
@serban-mihai No probs, also feel free to create a discussion. I've used framer a bit myself so I might be able to help or reproduce the issue in a sandbox :)

**Comment by serban-mihai** [comment]
Update: @nerdyman
Your tip about the transition by framer was correct, since the scale up animation the transition property was conflicting with the slider cursor, wouldn't get that without your tip 🚀 

I removed the wrapping element that was fading in the component and now the cursor is placed according to it's property value.
Looks like if there is a wrapping element to the <ReactCompareSlider /> with `style="opacity: 1; transform: none;"`it's going to break the initial cursor position as showed in my previous comment.

That `style` is appended to the wrapper by Framer Motion's animation:
```
const scaleUp = {
  visible: { opacity: 1, scale: 1, transition: { duration: 0.3 } },
  hidden: { opacity: 0, scale: 0, transition: { duration: 0.3 } },
};
```
But I cannot figure out how to bypass it to have the fade in along the correct cursor positioning so I'll leave it as it is for now.

Thanks again for the tip, this module is awesome! 👍🏻

**Comment by nerdyman** [comment]
@serban-mihai I think I've got a working version of what you want here https://codesandbox.io/s/react-compare-slider-simple-framer-motion-scale-forked-5uclo?file=/src/App.jsx

The trick to getting the slider position to be respected was to set the `initial` styles on the motion element to `opacity: 0` so it's rendered at its full size initially.

Hopefully this fits your use case.
